<a href="https://colab.research.google.com/github/alainnaim-code/p1c3_cr_ez_vos_premiers_arrays_avec_numpy.ipynb/blob/main/p1c3_cr_ez_vos_premiers_arrays_avec_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Créez vos premiers arrays avec Numpy

Tout au long de ce cours, nous allons nous mettre dans la peau d’une personne travaillant  dans un service data au sein d'une banque. Plus précisément, vous travaillez pour la filière gérant les différents prêts. L’objectif sera d’utiliser les connaissances acquises sur les librairies Python pour aider l’agence dans différentes tâches.

Pour cette première tâche, nous avons à notre disposition les revenus de 10 clients de notre banque. Vous aurez à utiliser les différentes manipulations présentées dans ce chapitre pour sélectionner certains revenus selon une condition spécifique et effectuer diverses opérations.

In [ ]:
import numpy as np

Considérons les revenus mensuels suivants :

In [ ]:
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

A partir de ces revenus, créez un array que vous nommerez `revenus` :

In [ ]:
import numpy as np
revenus = np.array(liste)
display(revenus)

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

Maintenant, créez un nouvel array `haut_revenus` dans lequel vous sélectionnerez l'ensemble des revenus supérieurs ou égal à 3000€ :

In [ ]:
haut_revenus = revenus [revenus>=3000]
display(haut_revenus)

array([3000, 5000])

Il est à présent temps de calculer quelques indicateurs :
- calculez dans un premier temps la somme des revenus **annuelle**. Pour rappel, les revenus listés ci dessus sont mensuels.
- calculez ensuite la moyenne des revenus des 10 clients

In [ ]:
somme_sum = revenus.sum()
somme_sum

np.int64(20672)

In [ ]:
somme = somme_sum * 12
somme

np.int64(248064)

In [ ]:
revenus_12 = revenus * 12
revenus_12

array([21600, 18000, 26400, 36000, 26064, 60000, 16800, 14400, 13200,
       15600])

In [ ]:
Somme =revenus_12.sum()
Somme

np.int64(248064)

In [ ]:
somme_K = round(somme / 1000)
print("La somme des revenus annuelle est :", somme_K, "K€")

La somme des revenus annuelle est : 248 K€


In [ ]:
print("La somme des revenus annuelle est d'environ:", 250, "K€")

La somme des revenus annuelle est d'environ: 250 K€


In [ ]:
somme_M = round(somme / 1_000_000,2)
print("La somme des revenus annuelle est de :", somme_M, "M€")

La somme des revenus annuelle est de : 0.25 M€


In [ ]:
moyenne = revenus.mean()
moyenne

np.float64(2067.2)

In [ ]:
print("Array avant :", revenus)
revenus[revenus == 1400] = 1600
print("Array après :", revenus)

Array avant : [1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
Array après : [1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]


Un de nos clients (dont les revenus mensuels s'élevaient jusque là à 1400€) vient de nous annoncer qu'il venait d'obtenir une promotion. Grâce à cette dernière, il a gagné 200€ sur son salaire mensuel. Effectuez cette modification au sein de votre array revenus.

Félicitation pour être arrivé au bout !

Si vous avez rencontré certains problèmes : aucune inquiétude :)

Vous pouvez à présent vous référer à la correction ci-contre qui propose une solution complète : [lien vers la solution](https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C3%20-%20Cr%C3%A9ez%20vos%20premiers%20arrays%20avec%20Numpy%20-%20correction.ipynb).